"""Declarative base + shared naming convention.

The naming convention is applied to every constraint/index Alembic creates, so
autogenerated migrations are stable and reviewable (``ck_``/``uq_``/``ix_``/
``fk_``/``pk_``) instead of relying on database-assigned names.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

#: Explicitly-named constraints/indexes keep their name; the convention only
#: fills in names for the ones we leave anonymous (every PK/FK). ``ck``/``uq``
#: are identity conventions on purpose: forgetting to name a CHECK or UNIQUE
#: constraint then fails loudly at import time instead of silently generating
#: ``ck_candles_ck_candle_high_ge_low``-style names.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


__all__ = ["NAMING_CONVENTION", "Base"]
