"""Migrations must apply, be drift-free, and be reversible."""

from __future__ import annotations

import ast
import re
from pathlib import Path

from alembic import command
from alembic.config import Config
from sqlalchemy import inspect
from sqlalchemy.engine import Engine

from app.models import ALL_TABLES

MIGRATION_FILE = Path(__file__).resolve().parents[2] / "migrations" / "versions" / "0001_initial_schema.py"


def test_upgrade_head_creates_every_table(migrated_db: Engine) -> None:
    tables = set(inspect(migrated_db).get_table_names())
    missing = ALL_TABLES - tables
    assert not missing, f"migration did not create: {sorted(missing)}"
    assert "alembic_version" in tables


def test_partial_index_exists_in_the_migrated_database(migrated_db: Engine) -> None:
    from sqlalchemy import text

    with migrated_db.connect() as conn:
        row = conn.execute(
            text("SELECT sql FROM sqlite_master WHERE type='index' AND name=:n"),
            {"n": "uq_positions_one_open_per_sym_tf"},
        ).fetchone()
    assert row is not None, "partial unique index missing after migration"
    assert "WHERE" in (row[0] or "").upper()
    assert "OPEN" in (row[0] or "")


def test_no_drift_between_models_and_migration(db_url: str) -> None:
    """``alembic check``: the migration is the single source of DDL truth."""
    cfg = Config(str(Path(__file__).resolve().parents[2] / "alembic.ini"))
    cfg.set_main_option("script_location", str(Path(__file__).resolve().parents[2] / "migrations"))
    cfg.set_main_option("sqlalchemy.url", db_url)
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected if a model changed without a migration


def test_downgrade_then_upgrade_is_reversible(alembic_config: Config) -> None:
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    from app.database.engine import build_engine

    engine = build_engine(alembic_config.get_main_option("sqlalchemy.url"))
    try:
        tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()
    assert ALL_TABLES & tables == set(), f"downgrade left tables behind: {tables}"

    command.upgrade(alembic_config, "head")
    engine = build_engine(alembic_config.get_main_option("sqlalchemy.url"))
    try:
        tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()
    assert tables >= ALL_TABLES


def test_migration_is_self_contained() -> None:
    """Migrations must not depend on application code (they outlive refactors).

    Checked structurally (imports via AST) rather than by string search, so the
    explanatory comments in the file do not trip the test.
    """
    source = MIGRATION_FILE.read_text(encoding="utf-8")
    tree = ast.parse(source)

    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)

    app_imports = {name for name in imported if name == "app" or name.startswith("app.")}
    assert app_imports == set(), f"migration imports application code: {app_imports}"
    assert "alembic" in " ".join(imported) or "alembic" in imported
    assert "sqlalchemy" in imported
    assert "create_all(" not in source
    assert "op.create_table(" in source


def test_migration_declares_the_expected_revision() -> None:
    source = MIGRATION_FILE.read_text(encoding="utf-8")
    assert re.search(r"^revision = ['\"]0001['\"]", source, re.MULTILINE)
    assert re.search(r"^down_revision = None", source, re.MULTILINE)


def test_scaled_integer_bounds_are_used_in_check_constraints() -> None:
    """Regression guard for the fixed-point bound bug.

    A ratio column stores 0.75 as 75000000, so a CHECK written as ``<= 1`` would
    reject every signal. The generated DDL must use the scaled bound.
    """
    source = MIGRATION_FILE.read_text(encoding="utf-8")
    assert "confidence >= 0 AND confidence <= 100000000" in source


def test_offline_sql_generation_works(alembic_config: Config) -> None:
    """`alembic upgrade --sql` must render DDL without a live connection.

    Offline rendering is a real property of the schema: it is what lets the DDL
    be reviewed, diffed and handed to a DBA. It holds for every revision that
    only creates or adds; revision ``0003`` narrows a UNIQUE constraint, and
    SQLite cannot drop a constraint in place, so alembic must rebuild the
    ``orders`` table ("batch" mode) — which requires a live connection to
    reflect the table. That one revision is therefore covered against a real
    database instead, by ``test_downgrade_then_upgrade_is_reversible`` and
    ``test_no_drift_between_models_and_migration``.
    """
    from io import StringIO

    buffer = StringIO()
    alembic_config.output_buffer = buffer
    command.upgrade(alembic_config, "0002", sql=True)
    sql = buffer.getvalue()
    assert "CREATE TABLE candles" in sql
    assert "uq_positions_one_open_per_sym_tf" in sql
    assert "strategy_config_hash" in sql
