"""initial schema (phase 1)

Creates the 16 phase-1 tables, including two invariants that cannot be
expressed as plain column constraints:

* ``uq_positions_one_open_per_sym_tf`` - a **partial** unique index enforcing
  "at most one OPEN position per (symbol, timeframe)"; SQLite and PostgreSQL
  accept the same ``WHERE state = 'OPEN'`` clause.
* ``ck_signals_target_after_candle`` - the database-level statement of "a signal
  may only be executed by the *next* candle, never by its own candle".

Also note ``ck_signals_confidence_range``: ratio columns are stored as scaled
integers (1.0 -> 100000000), so its bound is written in scaled units. See
app/database/types.py for the storage model.

Generated with ``alembic revision --autogenerate`` (not ``create_all``), so this
is reviewable DDL that later revisions diff against correctly.

Revision ID: 0001
Revises:
Create Date: 2026-09-29
"""
from __future__ import annotations

# Mapping note (kept explicit so the DDL is readable):
#   app.database.types.UTCDateTime  -> sa.DateTime(timezone=True)
#   app.database.types.FixedPoint   -> sa.BigInteger   (scaled integer: exact decimals)
# The revision is intentionally self-contained: it must keep running even if the
# application types are renamed or refactored. Regenerate normalisation with:
#   python scripts/normalize_migration.py <file>
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_observations',
    sa.Column('observation_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('at_candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('parsed_summary', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('observation_id', name=op.f('pk_ai_observations')),
    sa.UniqueConstraint('provider', 'symbol', 'timeframe', 'at_candle_open_time', name='uq_ai_observations_provider_candle')
    )
    with op.batch_alter_table('ai_observations', schema=None) as batch_op:
        batch_op.create_index('ix_ai_observations_sym_tf_time', ['symbol', 'timeframe', 'at_candle_open_time'], unique=False)

    op.create_table('candles',
    sa.Column('candle_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.BigInteger(), nullable=False),
    sa.Column('high', sa.BigInteger(), nullable=False),
    sa.Column('low', sa.BigInteger(), nullable=False),
    sa.Column('close', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("timeframe IN ('15m','1h','4h','1d')", name=op.f('ck_candles_timeframe_valid')),
    sa.CheckConstraint('close_time > open_time', name=op.f('ck_candles_close_after_open')),
    sa.CheckConstraint('high >= close', name=op.f('ck_candles_high_ge_close')),
    sa.CheckConstraint('high >= low', name=op.f('ck_candles_high_ge_low')),
    sa.CheckConstraint('high >= open', name=op.f('ck_candles_high_ge_open')),
    sa.CheckConstraint('low <= close', name=op.f('ck_candles_low_le_close')),
    sa.CheckConstraint('low <= open', name=op.f('ck_candles_low_le_open')),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name=op.f('ck_candles_prices_positive')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_candles_volume_nonneg')),
    sa.PrimaryKeyConstraint('candle_id', name=op.f('pk_candles')),
    sa.UniqueConstraint('symbol', 'timeframe', 'open_time', name='uq_candles_symbol_tf_open')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index('ix_candles_sym_tf_open', ['symbol', 'timeframe', 'open_time'], unique=False)

    op.create_table('configuration_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('software_version', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_versions')),
    sa.UniqueConstraint('scope', 'config_hash', name='uq_configuration_versions_scope_hash')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candle_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('name', 'dataset_hash', name='uq_data_sources_name_hash')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index('ix_data_sources_sym_tf', ['symbol', 'timeframe'], unique=False)

    op.create_table('health_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_checks'))
    )
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.create_index('ix_health_checks_component_time', ['component', 'checked_at'], unique=False)
        batch_op.create_index('ix_health_checks_status_time', ['status', 'checked_at'], unique=False)

    op.create_table('integrity_events',
    sa.Column('integrity_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('software_version', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('integrity_id', name=op.f('pk_integrity_events'))
    )
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.create_index('ix_integrity_events_code_time', ['code', 'detected_at'], unique=False)
        batch_op.create_index('ix_integrity_events_severity_time', ['severity', 'detected_at'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('at_candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.BigInteger(), nullable=False),
    sa.Column('reserved', sa.BigInteger(), nullable=False),
    sa.Column('open_position_value', sa.BigInteger(), nullable=False),
    sa.Column('unrealized_pnl', sa.BigInteger(), nullable=False),
    sa.Column('realized_pnl_cum', sa.BigInteger(), nullable=False),
    sa.Column('fees_cum', sa.BigInteger(), nullable=False),
    sa.Column('equity', sa.BigInteger(), nullable=False),
    sa.Column('peak_equity', sa.BigInteger(), nullable=False),
    sa.Column('drawdown_pct', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cash >= 0', name=op.f('ck_snapshots_cash_nonneg')),
    sa.CheckConstraint('drawdown_pct >= 0', name=op.f('ck_snapshots_drawdown_nonneg')),
    sa.CheckConstraint('equity = cash + reserved + open_position_value', name=op.f('ck_snapshots_equity_identity')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_snapshots_reserved_nonneg')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_portfolio_snapshots')),
    sa.UniqueConstraint('symbol', 'timeframe', 'at_candle_open_time', name='uq_snapshots_symbol_tf_time')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_sym_tf_time', ['symbol', 'timeframe', 'at_candle_open_time'], unique=False)

    op.create_table('positions',
    sa.Column('position_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('entry_price', sa.BigInteger(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_order_id', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('stop_loss', sa.BigInteger(), nullable=False),
    sa.Column('take_profit', sa.BigInteger(), nullable=False),
    sa.Column('entry_fee', sa.BigInteger(), nullable=False),
    sa.Column('unrealized_pnl', sa.BigInteger(), nullable=False),
    sa.Column('realized_pnl', sa.BigInteger(), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('strategy_config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=24), nullable=True),
    sa.CheckConstraint("close_reason IS NULL OR close_reason IN ('SL_HIT','TP_HIT','MANUAL','LIQUIDATION')", name=op.f('ck_positions_close_reason_valid')),
    sa.CheckConstraint("side IN ('BUY','SELL')", name=op.f('ck_positions_side_valid')),
    sa.CheckConstraint("state IN ('OPEN','CLOSING','CLOSED')", name=op.f('ck_positions_state_valid')),
    sa.CheckConstraint('entry_price > 0', name=op.f('ck_positions_entry_price_positive')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_positions_quantity_positive')),
    sa.CheckConstraint('stop_loss > 0 AND take_profit > 0', name=op.f('ck_positions_sl_tp_positive')),
    sa.PrimaryKeyConstraint('position_id', name=op.f('pk_positions'))
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_sym_tf_state', ['symbol', 'timeframe', 'state'], unique=False)
        batch_op.create_index('uq_positions_one_open_per_sym_tf', ['symbol', 'timeframe'], unique=True, sqlite_where=sa.text("state = 'OPEN'"), postgresql_where=sa.text("state = 'OPEN'"))

    op.create_table('scheduler_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('candles_processed', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_runs')),
    sa.UniqueConstraint('run_id', name=op.f('uq_scheduler_runs_run_id'))
    )
    with op.batch_alter_table('scheduler_runs', schema=None) as batch_op:
        batch_op.create_index('ix_scheduler_runs_name_started', ['name', 'started_at'], unique=False)
        batch_op.create_index('ix_scheduler_runs_status', ['status'], unique=False)

    op.create_table('signals',
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.BigInteger(), nullable=False),
    sa.Column('signal_candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_candle_close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_execution_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_execution_candle_id', sa.String(length=128), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('strategy_config_hash', sa.String(length=64), nullable=False),
    sa.Column('decision_version', sa.String(length=32), nullable=False),
    sa.Column('indicator_context', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('generation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('BUY','SELL','HOLD')", name=op.f('ck_signals_action_valid')),
    sa.CheckConstraint("timeframe IN ('15m','1h','4h','1d')", name=op.f('ck_signals_timeframe_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100000000', name=op.f('ck_signals_confidence_range')),
    sa.CheckConstraint('signal_candle_close_time > signal_candle_open_time', name=op.f('ck_signals_close_after_open')),
    sa.CheckConstraint('target_execution_open_time > signal_candle_open_time', name=op.f('ck_signals_target_after_candle')),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_sym_tf_candle', ['symbol', 'timeframe', 'signal_candle_open_time'], unique=False)
        batch_op.create_index('ix_signals_sym_tf_target', ['symbol', 'timeframe', 'target_execution_open_time'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('software_version', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('name', 'version', 'config_hash', name='uq_strategy_versions_nvh')
    )
    op.create_table('system_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('software_version', sa.String(length=16), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_system_events'))
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index('ix_system_events_entity', ['entity_id'], unique=False)
        batch_op.create_index('ix_system_events_sym_tf_time', ['symbol', 'timeframe', 'timestamp'], unique=False)
        batch_op.create_index('ix_system_events_type_time', ['event_type', 'timestamp'], unique=False)

    op.create_table('orders',
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('target_execution_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_execution_candle_id', sa.String(length=128), nullable=False),
    sa.Column('intended_quantity', sa.BigInteger(), nullable=False),
    sa.Column('intended_notional', sa.BigInteger(), nullable=False),
    sa.Column('stop_loss_price', sa.BigInteger(), nullable=True),
    sa.Column('take_profit_price', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('execution_provider', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_reason', sa.String(length=128), nullable=False),
    sa.CheckConstraint("execution_provider = 'paper'", name=op.f('ck_orders_paper_only')),
    sa.CheckConstraint("order_type IN ('MARKET_ON_OPEN')", name=op.f('ck_orders_type_valid')),
    sa.CheckConstraint("purpose IN ('ENTRY','EXIT')", name=op.f('ck_orders_purpose_valid')),
    sa.CheckConstraint("side IN ('BUY','SELL')", name=op.f('ck_orders_side_valid')),
    sa.CheckConstraint("state IN ('CREATED','PENDING','TARGET_REACHED','EXECUTED','TARGET_MISSED','CANCELLED')", name=op.f('ck_orders_state_valid')),
    sa.CheckConstraint('intended_notional > 0', name=op.f('ck_orders_notional_positive')),
    sa.CheckConstraint('intended_quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.CheckConstraint('stop_loss_price IS NULL OR stop_loss_price > 0', name=op.f('ck_orders_sl_positive')),
    sa.CheckConstraint('take_profit_price IS NULL OR take_profit_price > 0', name=op.f('ck_orders_tp_positive')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.signal_id'], name=op.f('fk_orders_signal_id_signals')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders')),
    sa.UniqueConstraint('signal_id', name=op.f('uq_orders_signal_id'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_state_target', ['state', 'target_execution_open_time'], unique=False)
        batch_op.create_index('ix_orders_sym_tf_created', ['symbol', 'timeframe', 'created_at'], unique=False)

    op.create_table('risk_decisions',
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('approved_quantity', sa.BigInteger(), nullable=True),
    sa.Column('approved_notional', sa.BigInteger(), nullable=True),
    sa.Column('stop_loss_price', sa.BigInteger(), nullable=True),
    sa.Column('take_profit_price', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome = 'REJECTED' OR (approved_quantity IS NOT NULL AND approved_notional IS NOT NULL)", name=op.f('ck_risk_decisions_approved_has_sizing')),
    sa.CheckConstraint("outcome IN ('APPROVED','REJECTED')", name=op.f('ck_risk_decisions_outcome_valid')),
    sa.CheckConstraint('approved_quantity IS NULL OR approved_quantity > 0', name=op.f('ck_risk_decisions_quantity_positive')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.signal_id'], name=op.f('fk_risk_decisions_signal_id_signals')),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_risk_decisions'))
    )
    op.create_table('executions',
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('execution_candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_candle_id', sa.String(length=128), nullable=False),
    sa.Column('raw_open_price', sa.BigInteger(), nullable=False),
    sa.Column('slippage_bps', sa.BigInteger(), nullable=False),
    sa.Column('actual_execution_price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('notional', sa.BigInteger(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.CheckConstraint("provider = 'paper'", name=op.f('ck_executions_paper_only')),
    sa.CheckConstraint("side IN ('BUY','SELL')", name=op.f('ck_executions_side_valid')),
    sa.CheckConstraint('actual_execution_price > 0', name=op.f('ck_executions_price_positive')),
    sa.CheckConstraint('fee >= 0', name=op.f('ck_executions_fee_nonneg')),
    sa.CheckConstraint('notional >= 0', name=op.f('ck_executions_notional_nonneg')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_executions_quantity_positive')),
    sa.CheckConstraint('raw_open_price > 0', name=op.f('ck_executions_raw_price_positive')),
    sa.CheckConstraint('slippage_bps >= 0', name=op.f('ck_executions_slippage_nonneg')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_executions_order_id_orders')),
    sa.PrimaryKeyConstraint('execution_id', name=op.f('pk_executions')),
    sa.UniqueConstraint('order_id', name=op.f('uq_executions_order_id'))
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index('ix_executions_sym_tf_candle', ['symbol', 'timeframe', 'execution_candle_open_time'], unique=False)

    op.create_table('trades',
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('position_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('entry_order_id', sa.String(length=64), nullable=False),
    sa.Column('exit_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('entry_price', sa.BigInteger(), nullable=False),
    sa.Column('exit_price', sa.BigInteger(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('holding_seconds', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.BigInteger(), nullable=False),
    sa.Column('exit_fee', sa.BigInteger(), nullable=False),
    sa.Column('gross_pnl', sa.BigInteger(), nullable=False),
    sa.Column('net_pnl', sa.BigInteger(), nullable=False),
    sa.Column('exit_reason', sa.String(length=24), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('strategy_config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("exit_reason IN ('SL_HIT','TP_HIT','MANUAL','LIQUIDATION')", name=op.f('ck_trades_exit_reason_valid')),
    sa.CheckConstraint("side IN ('BUY','SELL')", name=op.f('ck_trades_side_valid')),
    sa.CheckConstraint('entry_fee >= 0 AND exit_fee >= 0', name=op.f('ck_trades_fees_nonneg')),
    sa.CheckConstraint('entry_price > 0 AND exit_price > 0', name=op.f('ck_trades_prices_positive')),
    sa.CheckConstraint('holding_seconds >= 0', name=op.f('ck_trades_holding_nonneg')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_trades_quantity_positive')),
    sa.ForeignKeyConstraint(['entry_order_id'], ['orders.order_id'], name=op.f('fk_trades_entry_order_id_orders')),
    sa.ForeignKeyConstraint(['exit_order_id'], ['orders.order_id'], name=op.f('fk_trades_exit_order_id_orders')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.signal_id'], name=op.f('fk_trades_signal_id_signals')),
    sa.PrimaryKeyConstraint('trade_id', name=op.f('pk_trades'))
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_config_hash', ['strategy_config_hash'], unique=False)
        batch_op.create_index('ix_trades_sym_tf_exit_time', ['symbol', 'timeframe', 'exit_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_sym_tf_exit_time')
        batch_op.drop_index('ix_trades_config_hash')

    op.drop_table('trades')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index('ix_executions_sym_tf_candle')

    op.drop_table('executions')
    op.drop_table('risk_decisions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_sym_tf_created')
        batch_op.drop_index('ix_orders_state_target')

    op.drop_table('orders')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index('ix_system_events_type_time')
        batch_op.drop_index('ix_system_events_sym_tf_time')
        batch_op.drop_index('ix_system_events_entity')

    op.drop_table('system_events')
    op.drop_table('strategy_versions')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_sym_tf_target')
        batch_op.drop_index('ix_signals_sym_tf_candle')

    op.drop_table('signals')
    with op.batch_alter_table('scheduler_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduler_runs_status')
        batch_op.drop_index('ix_scheduler_runs_name_started')

    op.drop_table('scheduler_runs')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('uq_positions_one_open_per_sym_tf', sqlite_where=sa.text("state = 'OPEN'"), postgresql_where=sa.text("state = 'OPEN'"))
        batch_op.drop_index('ix_positions_sym_tf_state')

    op.drop_table('positions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_sym_tf_time')

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_integrity_events_severity_time')
        batch_op.drop_index('ix_integrity_events_code_time')

    op.drop_table('integrity_events')
    with op.batch_alter_table('health_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_health_checks_status_time')
        batch_op.drop_index('ix_health_checks_component_time')

    op.drop_table('health_checks')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_data_sources_sym_tf')

    op.drop_table('data_sources')
    op.drop_table('configuration_versions')
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candles_sym_tf_open')

    op.drop_table('candles')
    with op.batch_alter_table('ai_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_observations_sym_tf_time')

    op.drop_table('ai_observations')
    # ### end Alembic commands ###
