"""order: record strategy version and config hash

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 07:27:39.505729
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('strategy_config_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('strategy_config_hash')
        batch_op.drop_column('strategy_version')

    # ### end Alembic commands ###
