"""orders: uniqueness is per (signal, purpose) so exits can share the entry signal

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 07:28:22.619203
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_orders_signal_id'), type_='unique')
        batch_op.create_unique_constraint('uq_orders_signal_purpose', ['signal_id', 'purpose'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_signal_purpose', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_orders_signal_id'), ['signal_id'])

    # ### end Alembic commands ###
