#!/usr/bin/env python
"""Make an autogenerated Alembic revision self-contained.

Alembic renders our custom column types as ``app.database.types.UTCDateTime(...)``
and ``app.database.types.FixedPoint(...)``. That couples migrations to
application code, and a migration must keep working after application code is
refactored (that is the whole point of a migration).

This script rewrites those references into plain SQLAlchemy types:

    app.database.types.UTCDateTime(timezone=True) -> sa.DateTime(timezone=True)
    app.database.types.FixedPoint()               -> sa.BigInteger

Both mappings are loss-free for DDL: the UTC enforcement and the decimal scaling
happen in Python, not in the database.

Usage:
    python scripts/normalize_migration.py migrations/versions/0001_initial_schema.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPLACEMENTS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"app\.database\.types\.UTCDateTime\([^)]*\)"), "sa.DateTime(timezone=True)"),
    (re.compile(r"app\.database\.types\.FixedPoint\([^)]*\)"), "sa.BigInteger()"),
)

APP_IMPORT = re.compile(r"^import app\.database\.types.*$\n?", re.MULTILINE | re.UNICODE)

HEADER_NOTE = """
# Mapping note (kept explicit so the DDL is readable):
#   app.database.types.UTCDateTime  -> sa.DateTime(timezone=True)
#   app.database.types.FixedPoint   -> sa.BigInteger   (scaled integer: exact decimals)
# The revision is intentionally self-contained: it must keep running even if the
# application types are renamed or refactored. Regenerate normalisation with:
#   python scripts/normalize_migration.py <file>
"""


def normalize(path: Path) -> tuple[int, bool]:
    """Apply the type mapping. Returns (replacements, import_removed)."""
    source = path.read_text(encoding="utf-8")
    count = 0
    for pattern, replacement in REPLACEMENTS:
        source, hits = pattern.subn(replacement, source)
        count += hits

    import_removed = False
    if "import app.database.types" in source:
        source = APP_IMPORT.sub("", source)
        import_removed = True

    if count and "Mapping note" not in source:
        # Insert the note right before the first SQLAlchemy import block.
        marker = "from alembic import op"
        if marker in source:
            source = source.replace(marker, HEADER_NOTE.strip() + "\n" + marker, 1)
        else:
            source = source.replace(
                "import sqlalchemy as sa", "import sqlalchemy as sa\n" + HEADER_NOTE.strip(), 1
            )

    path.write_text(source, encoding="utf-8")
    return count, import_removed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("files", nargs="+", help="migration files to normalise")
    args = parser.parse_args(argv)

    for raw in args.files:
        path = Path(raw)
        if not path.exists():
            print(f"[normalize_migration] not found: {path}", file=sys.stderr)
            return 1
        count, import_removed = normalize(path)
        print(
            f"[normalize_migration] {path.name}: {count} type replacement(s), "
            f"app import removed={import_removed}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
